# Generated by Django 5.0.6 on 2024-06-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='done',
        ),
    ]
