# Generated by Django 5.0.6 on 2024-06-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
